blank_issues_enabled: false
contact_links:
  - name: Craft Cloud Issue
    url: https://craftcms.com/support-services
    about: Report a issue with Craft Cloud
  - name: Feature Request
    url: https://github.com/craftcms/cloud/discussions/new?category=feature-requests-enhancements
    about: Start a new discussion about your idea
